backend:
  name: git-gateway
  branch: main   # or master, depending on your repo branch

media_folder: "images"      # Where uploaded images are stored in the repo
public_folder: "/images"    # How images are accessed in the site

collections:
  - name: "products"
    label: "Products"
    files:
      - file: "products.json"
        label: "Product List"
        name: "productlist"
        fields:
          - { label: "Products", name: "products", widget: "list", fields: [
              { label: "Product Name", name: "name", widget: "string" },
              { label: "Price", name: "price", widget: "number" },
              { label: "Image", name: "image", widget: "image" },
              { label: "Description", name: "description", widget: "text" }
            ] }
